import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

// Heights between 6 and 50 (even numbers)
final SizedBox height6 = SizedBox(height: 6.h);
final SizedBox height8 = SizedBox(height: 8.h);
final SizedBox height10 = SizedBox(height: 10.h);
final SizedBox height12 = SizedBox(height: 12.h);
final SizedBox height14 = SizedBox(height: 14.h);
final SizedBox height16 = SizedBox(height: 16.h);
final SizedBox height18 = SizedBox(height: 18.h);
final SizedBox height20 = SizedBox(height: 20.h);
final SizedBox height22 = SizedBox(height: 22.h);
final SizedBox height24 = SizedBox(height: 24.h);
final SizedBox height26 = SizedBox(height: 26.h);
final SizedBox height28 = SizedBox(height: 28.h);
final SizedBox height30 = SizedBox(height: 30.h);
final SizedBox height32 = SizedBox(height: 32.h);
final SizedBox height34 = SizedBox(height: 34.h);
final SizedBox height36 = SizedBox(height: 36.h);
final SizedBox height38 = SizedBox(height: 38.h);
final SizedBox height40 = SizedBox(height: 40.h);
final SizedBox height42 = SizedBox(height: 42.h);
final SizedBox height44 = SizedBox(height: 44.h);
final SizedBox height46 = SizedBox(height: 46.h);
final SizedBox height48 = SizedBox(height: 48.h);
final SizedBox height50 = SizedBox(height: 50.h);

// Widths between 6 and 50 (even numbers)
final SizedBox width6 = SizedBox(width: 6.w);
final SizedBox width4 = SizedBox(width: 4.w);
final SizedBox width8 = SizedBox(width: 8.w);
final SizedBox width10 = SizedBox(width: 10.w);
final SizedBox width12 = SizedBox(width: 12.w);
final SizedBox width14 = SizedBox(width: 14.w);
final SizedBox width16 = SizedBox(width: 16.w);
final SizedBox width18 = SizedBox(width: 18.w);
final SizedBox width20 = SizedBox(width: 20.w);
final SizedBox width22 = SizedBox(width: 22.w);
final SizedBox width24 = SizedBox(width: 24.w);
final SizedBox width26 = SizedBox(width: 26.w);
final SizedBox width28 = SizedBox(width: 28.w);
final SizedBox width30 = SizedBox(width: 30.w);
final SizedBox width32 = SizedBox(width: 32.w);
final SizedBox width34 = SizedBox(width: 34.w);
final SizedBox width36 = SizedBox(width: 36.w);
final SizedBox width38 = SizedBox(width: 38.w);
final SizedBox width40 = SizedBox(width: 40.w);
final SizedBox width42 = SizedBox(width: 42.w);
final SizedBox width44 = SizedBox(width: 44.w);
final SizedBox width46 = SizedBox(width: 46.w);
final SizedBox width48 = SizedBox(width: 48.w);
final SizedBox width50 = SizedBox(width: 50.w);
